name: End-to-end test on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests on chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true