name: End-to-end test on Firefox
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests on Firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          headless: true
