name: WebRTC Nodejs CI

on: ["push", pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Continous integration with npm to extract packages
      run: npm ci
    - name: Build the node application
      run: npm run build --if-present
    - name: Lint the application with eslint script
      run: npm run lint
    - name: Test the application
      run: npm run test:ci
    - name: Login to docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the docker image
      run: docker build . --file Dockerfile --tag jbdiop/webrtc-app:$(date +%s)
    - name: Push image to dockerhub
      run: docker push ${{secrets.DOCKER_USER}}webrtc-app